package org.prettyjdbc.core.query;

import org.prettyjdbc.core.Unwrapable;
import org.prettyjdbc.core.query.scrollable_result.CachedScrollableResult;
import org.prettyjdbc.core.query.scrollable_result.ReadOnlyScrollableResult;

import java.math.BigDecimal;
import java.sql.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

/**
 * The <code>Query</code> represents a single operation to the relational database.
 * It extends the capabilities of the standard abstraction {@link java.sql.PreparedStatement}.
 * The lifecycle of a <code>Query</code> is very short and starts with the method {@link org.prettyjdbc.core.session.Session#createQuery(String)}.
 * Multiple SQL queries can be created within one {@link org.prettyjdbc.core.session.Session}.
 * <br>
 * To perform a native SQL query, use the method {@link Query#execute()} which will return the result as {@link ReadOnlyScrollableResult};
 * to update the data, use the method {@link Query#executeUpdate()};
 * to perform a batched query, use the method {@link Query#addBatch()} to add a batch
 * and {@link Query#executeBatch()} to apply it.
 *
 * @author Oleg Marchenko
 *
 * @see org.prettyjdbc.core.query.scrollable_result.ReadOnlyScrollableResult
 */

public class Query implements Unwrapable<PreparedStatement> {

    private final PreparedStatement preparedStatement;

    public Query(PreparedStatement preparedStatement) {
        this.preparedStatement = preparedStatement;
    }

    /**
     * Unwrapping {@link PreparedStatement} from the current <code>Query</code> for use outside.
     *
     * @return wrapped <code>PreparedStatement</code>
     */
    @Override
    public PreparedStatement unwrap() {
        return preparedStatement;
    }

    /**
     * Executes the SQL query and returns the {@link ReadOnlyScrollableResult} object generated by the query.
     *
     * @return a <code>ReadOnlyScrollableResult</code> object that contains the data produced by the query
     * @throws RuntimeException if a database access error occurs
     */
    public ReadOnlyScrollableResult execute() {
        try (ResultSet result = preparedStatement.executeQuery()) {
            return new CachedScrollableResult(result);
        }
        catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Executes the SQL query, which must be an SQL Data Manipulation Language (DML) statement,
     * such as <code>INSERT</code>, <code>UPDATE</code> or <code>DELETE</code>;
     * or an SQL statement that returns nothing, such as a DDL statement.
     *
     * @return either (1) the row count for SQL Data Manipulation Language (DML) statements
     *         or (2) 0 for SQL statements that return nothing
     * @throws RuntimeException if a database access error occurs
     */
    public int executeUpdate() {
        try {
            return preparedStatement.executeUpdate();
        }
        catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Adds a set of parameters to this <code>Query</code> object's batch of commands.
     *
     * @throws RuntimeException if a database access error occurs
     */
    public void addBatch() {
        try {
            preparedStatement.addBatch();
        }
        catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Submits a batch of commands to the database for execution and
     * if all commands execute successfully, returns an array of update counts.
     *
     * @return an array of update counts containing one element for each
     *         command in the batch
     * @throws RuntimeException if a database access error occurs
     */
    public int[] executeBatch() {
        try {
            return preparedStatement.executeBatch();
        }
        catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Returns <code>true</code> if the query is still active.
     * The query remains active until the method {@link org.prettyjdbc.core.session.Session#close()} has been called on it
     * or certain fatal errors have not occurred.
     *
     * @return <code>true</code> if this <code>Query</code> object is still active;
     *         <code>false</code> if it is inactive
     * @throws RuntimeException if a database access error occurs
     */
    public boolean isActive() {
        try {
            return !preparedStatement.isClosed();
        }
        catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Sets the designated parameter to the given Java <code>boolean</code> value.
     *
     * @param paramIndex the index of the parameter which must begin with 1
     * @param value the parameter value
     * @return instance of this query
     */
    public Query setParameter(int paramIndex, boolean value) {
        try {
            preparedStatement.setBoolean(paramIndex, value);
        }
        catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return this;
    }

    /**
     * Sets the designated parameter to the given Java <code>byte</code> value.
     *
     * @param paramIndex the index of the parameter which must begin with 1
     * @param value the parameter value
     * @return instance of this query
     */
    public Query setParameter(int paramIndex, byte value) {
        try {
            preparedStatement.setByte(paramIndex, value);
        }
        catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return this;
    }

    /**
     * Sets the designated parameter to the given Java <code>short</code> value.
     *
     * @param paramIndex the index of the parameter which must begin with 1
     * @param value the parameter value
     * @return instance of this query
     */
    public Query setParameter(int paramIndex, short value) {
        try {
            preparedStatement.setShort(paramIndex, value);
        }
        catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return this;
    }

    /**
     * Sets the designated parameter to the given Java <code>int</code> value.
     *
     * @param paramIndex the index of the parameter which must begin with 1
     * @param value the parameter value
     * @return instance of this query
     */
    public Query setParameter(int paramIndex, int value) {
        try {
            preparedStatement.setInt(paramIndex, value);
        }
        catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return this;
    }

    /**
     * Sets the designated parameter to the given Java <code>long</code> value.
     *
     * @param paramIndex the index of the parameter which must begin with 1
     * @param value the parameter value
     * @return instance of this query
     */
    public Query setParameter(int paramIndex, long value) {
        try {
            preparedStatement.setLong(paramIndex, value);
        }
        catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return this;
    }

    /**
     * Sets the designated parameter to the given Java <code>float</code> value.
     *
     * @param paramIndex the index of the parameter which must begin with 1
     * @param value the parameter value
     * @return instance of this query
     */
    public Query setParameter(int paramIndex, float value) {
        try {
            preparedStatement.setFloat(paramIndex, value);
        }
        catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return this;
    }

    /**
     * Sets the designated parameter to the given Java <code>double</code> value.
     *
     * @param paramIndex the index of the parameter which must begin with 1
     * @param value the parameter value
     * @return instance of this query
     */
    public Query setParameter(int paramIndex, double value) {
        try {
            preparedStatement.setDouble(paramIndex, value);
        }
        catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return this;
    }

    /**
     * Sets the designated parameter to the given Java <code>java.math.BigDecimal</code> value.
     *
     * @param paramIndex the index of the parameter which must begin with 1
     * @param value the parameter value
     * @return instance of this query
     */
    public Query setParameter(int paramIndex, BigDecimal value) {
        try {
            preparedStatement.setBigDecimal(paramIndex, value);
        }
        catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return this;
    }

    /**
     * Sets the designated parameter to the given Java <code>String</code> value.
     *
     * @param paramIndex the index of the parameter which must begin with 1
     * @param value the parameter value
     * @return instance of this query
     */
    public Query setParameter(int paramIndex, String value) {
        try {
            preparedStatement.setString(paramIndex, value);
        }
        catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return this;
    }

    /**
     * Sets the designated parameter to the given Java array of bytes.
     *
     * @param paramIndex the index of the parameter which must begin with 1
     * @param value the parameter value
     * @return instance of this query
     */
    public Query setParameter(int paramIndex, byte[] value) {
        try {
            preparedStatement.setBytes(paramIndex, value);
        }
        catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return this;
    }

    /**
     * Sets the designated parameter to the given Java <code>java.sql.Date</code> value.
     *
     * @param paramIndex the index of the parameter which must begin with 1
     * @param value the parameter value
     * @return instance of this query
     */
    public Query setParameter(int paramIndex, Date value) {
        try {
            preparedStatement.setDate(paramIndex, value);
        }
        catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return this;
    }

    /**
     * Sets the designated parameter to the given Java <code>java.time.LocalDate</code> value as <code>java.sql.Date</code>.
     *
     * @param paramIndex the index of the parameter which must begin with 1
     * @param value the parameter value
     * @return instance of this query
     */
    public Query setParameter(int paramIndex, LocalDate value) {
        Date date = null;
        if (value != null) {
            date = Date.valueOf(value);
        }
        return setParameter(paramIndex, date);
    }

    /**
     * Sets the designated parameter to the given Java <code>java.sql.Time</code> value.
     *
     * @param paramIndex the index of the parameter which must begin with 1
     * @param value the parameter value
     * @return instance of this query
     */
    public Query setParameter(int paramIndex, Time value) {
        try {
            preparedStatement.setTime(paramIndex, value);
        }
        catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return this;
    }

    /**
     * Sets the designated parameter to the given Java <code>java.time.LocalTime</code> value as <code>java.sql.Time</code>.
     *
     * @param paramIndex the index of the parameter which must begin with 1
     * @param value the parameter value
     * @return instance of this query
     */
    public Query setParameter(int paramIndex, LocalTime value) {
        Time time = null;
        if (value != null) {
            time = Time.valueOf(value);
        }
        return setParameter(paramIndex, time);
    }

    /**
     * Sets the designated parameter to the given Java <code>java.sql.Timestamp</code> value.
     *
     * @param paramIndex the index of the parameter which must begin with 1
     * @param value the parameter value
     * @return instance of this query
     */
    public Query setParameter(int paramIndex, Timestamp value) {
        try {
            preparedStatement.setTimestamp(paramIndex, value);
        }
        catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return this;
    }

    /**
     * Sets the designated parameter to the given Java <code>java.time.LocalDateTime</code> value as <code>java.sql.Timestamp</code>.
     *
     * @param paramIndex the index of the parameter which must begin with 1
     * @param value the parameter value
     * @return instance of this query
     */
    public Query setParameter(int paramIndex, LocalDateTime value) {
        Timestamp timestamp = null;
        if (value != null) {
            timestamp = Timestamp.valueOf(value);
        }
        return setParameter(paramIndex, timestamp);
    }

    /**
     * Sets the value of the designated parameter with the given object.
     *
     * @param paramIndex the index of the parameter which must begin with 1
     * @param value the parameter value
     * @return instance of this query
     */
    public Query setParameter(int paramIndex, Object value) {
        try {
            preparedStatement.setObject(paramIndex, value);
        }
        catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return this;
    }
}
